[auto-ipv6] fix dyndns,olsrd restart,remove radvd,add dnsmasq for ra and dhcpv6, THX Soma

diff --git a/utils/auto-ipv6/src/30-auto-ipv6 b/utils/auto-ipv6/src/30-auto-ipv6
--- a/utils/auto-ipv6/src/30-auto-ipv6
+++ b/utils/auto-ipv6/src/30-auto-ipv6
@@ -95,8 +95,8 @@ olsrd_find_plugin(){
 find_public_ip(){
 	local ret
 	#FIXME
-	#ret="$(wget -q -O - http://checkip.dyndns.org/index.html | awk {'print $6'} | sed 's/<.*$//')"
-	ret="$(wget -q -O - http://204.13.248.70/index.html | awk {'print $6'} | sed 's/<.*$//')"
+	ret="$(wget -q -O - http://checkip.dyndns.org/index.html | awk {'print $6'} | sed 's/<.*$//')"
+	#ret="$(wget -q -O - http://204.13.248.70/index.html | awk {'print $6'} | sed 's/<.*$//')"
 	echo "$ret"
 }
 local IP4_LOCAL_IF="$IP4_LOCAL"
@@ -115,13 +115,13 @@ fi
 # change umask of /var/state files for httpd 
 umask 022
 
-IP6_SUFIX=$(printf "2002:%02x%02x:%02x%02x" $(echo $IP4_LOCAL|sed 's/\./ /g'))
-logger -t auto-ipv6 "Applying IPv6 Sufix $IP6_SUFIX"
+IP6_SUFFIX=$(printf "2002:%02x%02x:%02x%02x" $(echo $IP4_LOCAL|sed 's/\./ /g'))
+logger -t auto-ipv6 "Applying IPv6 Sufix $IP6_SUFFIX"
 ifconfig tun6to4 down 2&>1 1>/dev/null
 ip tunnel del tun6to4 2&>1 1>/dev/null
 ip tunnel add tun6to4 mode sit remote any local $IP4_LOCAL_IF ttl 64
 ifconfig tun6to4 up
-ifconfig tun6to4 "$IP6_SUFIX""::1/16"
+ifconfig tun6to4 "$IP6_SUFFIX""::1/16"
 route -A inet6 add "::192.88.99.1" dev tun6to4
 route -A inet6 add "2000::/3" gw "::192.88.99.1" dev tun6to4 metric 1
 route -A inet6 add "::/0" gw "::192.88.99.1" dev tun6to4 metric 1
@@ -133,58 +133,79 @@ config_load network
 interfaces=""
 config_foreach net_find_iface interface
 logger -t auto-ipv6 "found $interfaces"
-restart_radvd=0
-restart_olsrd=0
-restart_crond=0
-hna6s="::"
+local restart_dnsmasq=0
+local restart_olsrd=0
+local restart_crond=0
+local hna6s="::"
+
+[ -h /etc/dnsmasq.conf ] || ( rm -rf /etc/dnsmasq.conf ; ln -s /tmp/dnsmasq.conf /etc/dnsmasq.conf )
+> /tmp/dnsmasq.conf
+echo "enable-ra" >> /tmp/dnsmasq.conf
+echo "dhcp-option=option6:dns-server,[::]" >> /tmp/dnsmasq.conf
+echo "dhcp-option=option6:domain-search,olsr" >> /tmp/dnsmasq.conf
+restart_dnsmasq=1
+
 for i in $(echo $interfaces) ; do
 	[ "$(uci get network.$i.proto)" == "static" ] || continue
 	DEV="$(uci -q -p/var/state get network.$i.ifname)"
 	[ -z "$DEV" ]  && {
-		logger -t auto-ipv6 "uci Device Not Found IP6_SUFIX $IP6_SUFIX interfaces $i DEV $DEV check your uci config"
+		logger -t auto-ipv6 "uci Device Not Found IP6_SUFFIX $IP6_SUFFIX interfaces $i DEV $DEV check your uci config"
 		continue
 	}
 	grep -q $DEV /proc/net/dev || {
-		logger -t auto-ipv6 "Device Not Found IP6_SUFIX $IP6_SUFIX interfaces $i DEV $DEV check your uci config"
+		logger -t auto-ipv6 "Device Not Found IP6_SUFFIX $IP6_SUFFIX interfaces $i DEV $DEV check your uci config"
 		continue
 	}
 	IP6_UCI=$(uci get network.$i.ip6addr)
 	if [ $(echo $IP6_UCI | grep -i fdca) ] ; then
 		uci set network.$i.ip6addr_fdca="$IP6_UCI"
-		IP6_UCI=''
 	fi
-	IP6_OLDSUFIX="$(echo $IP6_UCI | cut -d ':' -f -3)"
+	IP6_OLDSUFFIX="$(echo $IP6_UCI | cut -d ':' -f -3)"
 	IP6_OLDUNIQ="$(echo $IP6_UCI | cut -d ':' -f 4)"
-	[ -z $IP6_OLDSUFIX ] || {
-		[ "$IP6_SUFIX" == "$IP6_OLDSUFIX" ] && ifconfig "$DEV" | grep -q -e "$IP6_SUFIX"".*1\/64" && {
-			hna6s="$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::"" $hna6s"
+	if [ "$IP6_SUFFIX" == "$IP6_OLDSUFFIX" ] ; then
+		if ifconfig "$DEV" | grep -q -e "$IP6_SUFFIX"".*1\/64" > /dev/null ; then
+			hna6s="$IP6_OLDSUFFIX:$IP6_OLDUNIQ::"" $hna6s"
+			echo "dhcp-range=$DEV,$IP6_OLDSUFFIX:$IP6_OLDUNIQ::100,$IP6_OLDSUFFIX:$IP6_OLDUNIQ::200,slaac,deprecated,64,600s" >> /tmp/dnsmasq.conf
+			restart_dnsmasq=1
+			logger -t auto-ipv6 "Found IP6_SUFFIX $IP6_OLDSUFFIX on interfaces $i DEV $DEV no update"
 			continue
-		}
-	}
+		fi
+	fi
+
 	#Uniq 4Bybte from urandom
 	IP6_UNIQ="$(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4)"
+	case $IP6_UNIQ in 
+		000*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 4) ;; 
+		00*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 3-4) ;; 
+		0*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 2-4) ;;
+	esac
+	IP6_ADDRESS="${IP6_SUFFIX}:${IP6_UNIQ}::1/64"
 
-	[ -z $IP6_OLDSUFIX ] || {
-		ifconfig "$DEV" del "$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::1/64"
-	}
-
+	local ifconfig_add=1
 	for j in $(ifconfig $DEV | grep Scope:Global | cut -d ' ' -f 13 ) ; do
-		ifconfig "$DEV" del "$j"
+		if ! [ $j == $IP6_ADDRESS ] ; then
+			ifconfig "$DEV" del "$j"
+		fi
 	done
 
-	sysctl -w "net.ipv6.conf.$DEV.autoconf=0"
-	sysctl -w "net.ipv6.conf.$DEV.accept_redirects=0"
-	sysctl -w "net.ipv6.conf.$DEV.accept_ra=0"
-	sysctl -w "net.ipv6.conf.$DEV.accept_ra_defrtr=0"
-	sysctl -w "net.ipv6.conf.$DEV.accept_ra_pinfo=0"
-	sysctl -w "net.ipv6.conf.$DEV.accept_source_route=0"
-	ifconfig "$DEV" add "$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
-	uci -P /var/state set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
-	uci set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
-	uci commit network
-	hna6s="$IP6_SUFIX"":""$IP6_UNIQ""::"" $hna6s"
+	if [ $ifconfig_add -eq 1 ] ; then
+		ifconfig "$DEV" add "$IP6_ADDRESS"
+		logger -t auto-ipv6 "ifconfig $DEV add $IP6_ADDRESS"
+		uci -P /var/state set network.$i.ip6addr="$IP6_ADDRESS"
+		uci set network.$i.ip6addr="$IP6_ADDRESS"
+		uci commit network
+		sysctl -w "net.ipv6.conf.$DEV.forwarding=1"
+		sysctl -w "net.ipv6.conf.$DEV.autoconf=0"
+		sysctl -w "net.ipv6.conf.$DEV.accept_ra=0"
+		sysctl -w "net.ipv6.conf.$DEV.accept_ra_defrtr=0"
+		sysctl -w "net.ipv6.conf.$DEV.accept_ra_pinfo=0"
+	fi
 
-	restart_radvd=1
+	hna6s="$IP6_SUFFIX"":""$IP6_UNIQ""::"" $hna6s"
+
+	echo "dhcp-range=$DEV,$IP6_SUFFIX:$IP6_UNIQ::100,$IP6_SUFFIX:$IP6_UNIQ::200,slaac,deprecated,64,600s" >> /tmp/dnsmasq.conf
+	restart_dnsmasq=1
+
 done
 
 if [ "6and4" == "$(uci get olsrd.@olsrd[0].IpVersion)" ] ; then
@@ -223,6 +244,9 @@ grep -q ping6 /etc/crontabs/root || {
 	restart_crond=1
 	}
 
+# clear all config variables here. else they will leak into the olsrd init script
+config_clear
+
 if [ $restart_crond -eq 1 ] ; then
 	if ! [ -z "$(pidof crond)" ] ; then
 		/etc/init.d/cron stop
@@ -230,18 +254,22 @@ if [ $restart_crond -eq 1 ] ; then
 		/etc/init.d/cron start
 	fi
 fi
-if [ $restart_radvd -eq 1 ] ; then
-	if ! [ -z "$(pidof radvd)" ] ; then
-		/etc/init.d/radvd stop
-		killall -9 radvd
-		/etc/init.d/radvd start
+if [ $restart_dnsmasq -eq 1 ] ; then
+	if ! [ -z "$(pidof dnsmasq)" ] ; then
+		logger -t auto-ipv6 "Restarting dnsmasq..."
+		/etc/init.d/dnsmasq restart
 	fi
 fi
 if [ $restart_olsrd -eq 1 ] ; then
 	if ! [ -z "$(pidof olsrd)" ] ; then
-		/etc/init.d/olsrd stop
-		killall -9 olsrd
-		/etc/init.d/olsrd start
+		logger -t auto-ipv6 "Restarting olsrd..."
+		#FIXME if restart via cron olsrd is not listen on :::2006
+		(
+			/etc/init.d/olsrd restart
+			sleep 1
+			/etc/init.d/olsrd restart
+		) &
+		#FIXME
 	fi
 fi
 lock -u /var/run/auto-ipv6.lock
